### ISSUE TITLE
Error when opening plugin (unexpected type 'float' in QRect constructor)

### ISSUE THREAD

**Issue by ster-sjo** [sourcepole/qgis-instantprint-plugin#38]
When we open the plugin we encounter the following error:

2024-10-11T11:31:55     WARNING    Traceback (most recent call last):
              File "C:\Users/sjo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\instantprint\InstantPrintTool.py", line 166, in __selectLayout
              self.__createRubberBand()
              File "C:\Users/sjo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\instantprint\InstantPrintTool.py", line 176, in __createRubberBand
              self.rubberband.setToCanvasRectangle(self.__canvasRect(self.rect))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/sjo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\instantprint\InstantPrintTool.py", line 251, in __canvasRect
              return QRect(p1.x(), p1.y(), p2.x() - p1.x(), p2.y() - p1.y())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             TypeError: arguments did not match any overloaded call:
              QRect(): too many arguments
              QRect(aleft: int, atop: int, awidth: int, aheight: int): argument 1 has unexpected type 'float'
              QRect(atopLeft: QPoint, abottomRight: QPoint): argument 1 has unexpected type 'float'
              QRect(atopLeft: QPoint, asize: QSize): argument 1 has unexpected type 'float'
              QRect(a0: QRect): argument 1 has unexpected type 'float'

**Comment by tpo** [comment]
It would be helpful to know the version of the plugin and the version of QGIS

**Comment by SIG-CLCL** [comment]
Hello,
I have the same problem : QGIS 3.34.11 and Plugin Version 3.0.0. Any idea ?

**Comment by tpo** [comment]
FWIW: I have installed the plugin on a QGIS 3.34.13 with Plugin Version 3.0.0 on Debian Linux bookworm with Python 3.11.2 and the Plugin Window pops up without any problems.

**Comment by gducerf** [comment]
It seems that the QRect constructor no longer supports floats. Floats must be casted to integers.
Don't know why it's not casted since the latest versions of QGIS 3.34.
Is there anybody to accept the pull request please?

**Comment by manisandro** [comment]
Thanks, I've merged the PR and published v3.0.1
